export enum Key {
    Null = 0,        // Key: NULL, used for no key pressed
    Quote = 39,       // Key: '
    Comma = 44,       // Key: ,
    Minus = 45,       // Key: -
    Period = 46,       // Key: .
    Slash = 47,       // Key: /
    Digit0 = 48,       // Key: 0
    Digit1 = 49,       // Key: 1
    Digit2 = 50,       // Key: 2
    Digit3 = 51,       // Key: 3
    Digit4 = 52,       // Key: 4
    Digit5 = 53,       // Key: 5
    Digit6 = 54,       // Key: 6
    Digit7 = 55,       // Key: 7
    Digit8 = 56,       // Key: 8
    Digit9 = 57,       // Key: 9
    Semicolon = 59,       // Key: ;
    Equal = 61,       // Key: =
    KeyA = 65,       // Key: A | a
    KeyB = 66,       // Key: B | b
    KeyC = 67,       // Key: C | c
    KeyD = 68,       // Key: D | d
    KeyE = 69,       // Key: E | e
    KeyF = 70,       // Key: F | f
    KeyG = 71,       // Key: G | g
    KeyH = 72,       // Key: H | h
    KeyI = 73,       // Key: I | i
    KeyJ = 74,       // Key: J | j
    KeyK = 75,       // Key: K | k
    KeyL = 76,       // Key: L | l
    KeyM = 77,       // Key: M | m
    KeyN = 78,       // Key: N | n
    KeyO = 79,       // Key: O | o
    KeyP = 80,       // Key: P | p
    KeyQ = 81,       // Key: Q | q
    KeyR = 82,       // Key: R | r
    KeyS = 83,       // Key: S | s
    KeyT = 84,       // Key: T | t
    KeyU = 85,       // Key: U | u
    KeyV = 86,       // Key: V | v
    KeyW = 87,       // Key: W | w
    KeyX = 88,       // Key: X | x
    KeyY = 89,       // Key: Y | y
    KeyZ = 90,       // Key: Z | z
    BracketLeft = 91,       // Key: [
    Backslash = 92,       // Key: '\'
    BracketRight = 93,       // Key: ]
    Backquote = 96,       // Key: `
    F1 = 290,      // Key: F1
    F2 = 291,      // Key: F2
    F3 = 292,      // Key: F3
    F4 = 293,      // Key: F4
    F5 = 294,      // Key: F5
    F6 = 295,      // Key: F6
    F7 = 296,      // Key: F7
    F8 = 297,      // Key: F8
    F9 = 298,      // Key: F9
    F10 = 299,      // Key: F10
    F11 = 300,      // Key: F11
    F12 = 301,      // Key: F12
}